import { Transaction } from "@/types/transaction";

export const TransactionsData: Transaction[] = [
    {
        id: 1,
        name: "Davy Jpnes",
        paymentMethod: "MasterCard **** 9918",
        cardType: "mastercard",
        amount: "₹1234",
        date: "17 Feb, 25",
        status: "success",
        icon: require("../assets/images/transactions/mastercard.png"),
    },
    {
        id: 2,
        name: "John Doe",
        paymentMethod: "Gpay **** 9918",
        cardType: "gpay",
        amount: "₹542",
        date: "16 Feb, 25",
        status: "failed",
        icon: require("../assets/images/transactions/gpay.png"),
    },
    {
        id: 3,
        name: "William",
        paymentMethod: "PhonePe **** 9918",
        cardType: "phonepe",
        amount: "₹234",
        date: "13 Feb, 25",
        status: "success",
        icon: require("../assets/images/transactions/phonepe.png"),
    },
    {
        id: 4,
        name: "Margaret",
        paymentMethod: "Amazon pay **** 9918",
        cardType: "amazonpay",
        amount: "₹780",
        date: "12 Feb, 25",
        status: "success",
        icon: require("../assets/images/transactions/amazonpay.png"),
    },
    {
        id: 5,
        name: "Robert",
        paymentMethod: "Mobikwik **** 9918",
        cardType: "mobikwik",
        amount: "₹3400",
        date: "11 Feb, 25",
        status: "failed",
        icon: require("../assets/images/transactions/mobikwik.png"),
    },
    {
        id: 6,
        name: "Mildred",
        paymentMethod: "VisaCard **** 9918",
        cardType: "visa",
        amount: "₹2150",
        date: "10 Feb, 25",
        status: "success",
        icon: require("../assets/images/transactions/visa.png"),
    },
    {
        id: 7,
        name: "Clarence",
        paymentMethod: "Paytm **** 9918",
        cardType: "paytm",
        amount: "₹1150",
        date: "07 Feb, 25",
        status: "success",
        icon: require("../assets/images/transactions/paytm.png"),
    },
    {
        id: 8,
        name: "Richard",
        paymentMethod: "MasterCard **** 9918",
        cardType: "mastercard",
        amount: "₹6500",
        date: "04 Feb, 25",
        status: "success",
        icon: require("../assets/images/transactions/mastercard.png"),
    },
];